name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10, 11, 12, 13, 14]
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }} and ${{ matrix.os }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Node.js version
        run: node -v
      - name: npm version
        run: npm -v
      - name: Run eslint
        run: npm run lint
      - name: Run prettier
        run: npm run prettier
      - name: Run tests
        run: npm test
      - name: Test prepublish script
        run: npm run prepublishOnly
      - name: Test postpublish script
        run: npm run postpublish
      - name: Test coverage
        run: npm run coverage
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
